name: Publish (Snapshot)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The npm tag to publish to"
        required: true

jobs:
  publish_snapshot:
    name: Publish (Snapshot)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: true # needed for git push

      - uses: ./.github/actions/setup-deps

      - name: version packages
        run: yarn changeset version --snapshot ${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: git commit
        run: |
          git config --global user.name 'Thinkmill Release Bot'
          git config --global user.email 'automation+github@thinkmill.com.au'
          git commit -a -m 'rc'

      - run: yarn build

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: npm publish, git tag
        run: yarn changeset publish --tag ${{ inputs.tag }}

      # reset, then push the dangling commit
      - name: git push
        run: |
          git reset HEAD~1 --hard
          git push origin --tags
